
[[constraint]]
name = "github.com/openshift/client-go"
branch = "release-3.10"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/openshift/api"
  version = "3.9.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.12.2"

[[constraint]]
  branch = "release-1.11"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-1.11"
  name = "k8s.io/api"

#[[constraint]]
#  name = "github.com/fsouza/go-dockerclient"
#  version = "1.2.2"

[[override]]
  name = "github.com/docker/docker"
  revision = "a422774e593b33bd287d9890544ad9e09b380d8c"

[prune]
  go-tests = true
  unused-packages = true
