name: Go Builder

on:
  push:
    #paths-ignore:
     # - 'docs/**'
     # - '.github/**'
     # - 'templates/**'
  pull_request:
    #paths-ignore:
    #  - 'docs/**'
    #  - '.github/**'
    #  - 'templates/**'

jobs:
  build:
    name: Build mg
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
        id: go

      - name: Go modules cache
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cd mg && ./build.sh
        shell: bash